name: TestPlugin0
version: '${project.version}'
main: testplugin0.testplugin0.TestPlugin0
api-version: 1.15

commands:
  crasher:
    description: idk
    aliases: [crash]
  fly:
    usage: /fly
    description: サバイバルでも飛べるようになります
  medic:
    usage: /medic
    description: あなたを回復します
  reboot:
    usage: /reboot
    description: サーバー再起動テキストを全体に送信します[再起動は手動でお願いします]
  allkick[利用不可]:
    description: すべてのプレイヤーをkickします[利用不可]
  permissions:
    allkick.use:
      description: allkickの権限
      default: op
    allkick.ignore:
      description: allkickで蹴られない
      default: op
    allkick.*:
      description: allkickのすべての権限
      default: op
      children:
        allkick.use: true
        allkick.ignore: true